import { useLayoutEffect, useRef } from 'react'

import WorkflowIterationDemo from '../features/workflow-iteration/WorkflowIterationDemo'
import styles from '../features/workflow-iteration/workflow-iteration.module.css'

const STAGE_WIDTH = 1920
const STAGE_HEIGHT = 1080

export default function WorkflowIterationSection() {
  const stageRef = useRef<HTMLDivElement>(null)

  useLayoutEffect(() => {
    const stage = stageRef.current
    const host = stage?.parentElement
    if (!stage || !host) return

    const fitStage = () => {
      const scale = Math.min(
        host.clientWidth / STAGE_WIDTH,
        host.clientHeight / STAGE_HEIGHT,
      )
      stage.style.setProperty('--workflow-scale', String(scale))
    }

    fitStage()
    const observer = new ResizeObserver(fitStage)
    observer.observe(host)
    return () => observer.disconnect()
  }, [])

  return (
    <section className={styles.workflowSection} id="workflow-iteration" aria-label="Workflow iteration demo">
      <div className={styles.demoMount}>
        <div className={styles.demoCanvas} ref={stageRef}>
          <WorkflowIterationDemo />
        </div>
      </div>

      <div className={styles.demoEvidence}>
        <p>
          Many AI video tools can generate impressive clips, but none has publicly demonstrated a fully
          agentic end-to-end system validated by real market response. We have done so with <strong>Orchia</strong>,
          {' '}a recursive multi-agent system that produces videos end to end. It automates creative production
          from idea to final video with minimal human work. It is also self-evolving, meaning that the quality of
          its output improves significantly in a very short time. We show that Orchia not only works, but works
          impressively. In three weeks, we posted 10 videos, each about one minute long, from a new account, all
          generated by Orchia. With no marketing, they generated <strong>5.6M+ organic views</strong>, achieved a
          {' '}<strong>48.9% average completion rate</strong>, and gained <strong>1,423 new followers</strong>.
        </p>
      </div>
    </section>
  )
}
